"""adding hash of the text2summarize

Revision ID: 38049e19b1ec
Revises: dd3ff32ed28c
Create Date: 2023-04-01 18:49:06.362456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38049e19b1ec'
down_revision = 'dd3ff32ed28c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry__post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test2summarize_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_entry__post_test2summarize_hash'), ['test2summarize_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry__post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry__post_test2summarize_hash'))
        batch_op.drop_column('test2summarize_hash')

    # ### end Alembic commands ###
