"""Corrected variable name to text2summarize

Revision ID: acaf887cbec7
Revises: 38049e19b1ec
Create Date: 2023-04-05 21:35:21.132983

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'acaf887cbec7'
down_revision = 'e7fca5d28c07'
branch_labels = None
depends_on = None


#def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
 #   with op.batch_alter_table('entry__post', schema=None) as batch_op:
 #       batch_op.add_column(sa.Column('text2summarize', sa.String(length=214748364), nullable=True))
 #       batch_op.add_column(sa.Column('text2summarize_hash', sa.String(length=64), nullable=True))
 #       batch_op.drop_index('ix_entry__post_test2summarize')
 #       batch_op.drop_index('ix_entry__post_test2summarize_hash')
 #       batch_op.create_index(batch_op.f('ix_entry__post_text2summarize'), ['text2summarize'], unique=False)
 #       batch_op.create_index(batch_op.f('ix_entry__post_text2summarize_hash'), ['text2summarize_hash'], unique=False)
 #       batch_op.drop_column('test2summarize_hash')
 #       batch_op.drop_column('test2summarize')

    # ### end Alembic commands ###

def upgrade():
    # Step 1: Create a new temporary table with the updated column names
    op.create_table(
        "entry__post__temp",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("timestamp", sa.DateTime, index=True, default=datetime.utcnow),
        sa.Column("posttype", sa.Integer, index=True),
        sa.Column("url", sa.String(2048), index=True),
        sa.Column("text2summarize", sa.String(214748364), index=True),
        sa.Column("text2summarize_hash", sa.String(64), index=True),
        sa.Column("openAIsummary", sa.String(214748), index=True),
    )

    # Step 2: Copy the data from the old table to the new table
    op.execute("INSERT INTO entry__post__temp (id, timestamp, posttype, url, text2summarize, text2summarize_hash, openAIsummary) SELECT id, timestamp, posttype, url, test2summarize, test2summarize_hash, openAIsummary FROM entry__post")

    # Step 3: Drop the old table
    op.drop_table("entry__post")

    # Step 4: Rename the temporary table to the original table name
    op.rename_table("entry__post__temp", "entry__post")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry__post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test2summarize', sa.VARCHAR(length=214748364), nullable=True))
        batch_op.add_column(sa.Column('test2summarize_hash', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_entry__post_text2summarize_hash'))
        batch_op.drop_index(batch_op.f('ix_entry__post_text2summarize'))
        batch_op.create_index('ix_entry__post_test2summarize_hash', ['test2summarize_hash'], unique=False)
        batch_op.create_index('ix_entry__post_test2summarize', ['test2summarize'], unique=False)
        batch_op.drop_column('text2summarize_hash')
        batch_op.drop_column('text2summarize')

    # ### end Alembic commands ###
