"""Corrected variable name to text2summarize

Revision ID: acaf887cbec7
Revises: 38049e19b1ec
Create Date: 2023-04-05 21:35:21.132983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acaf887cbec7'
down_revision = '38049e19b1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry__post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text2summarize', sa.String(length=214748364), nullable=True))
        batch_op.add_column(sa.Column('text2summarize_hash', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_entry__post_test2summarize')
        batch_op.drop_index('ix_entry__post_test2summarize_hash')
        batch_op.create_index(batch_op.f('ix_entry__post_text2summarize'), ['text2summarize'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry__post_text2summarize_hash'), ['text2summarize_hash'], unique=False)
        batch_op.drop_column('test2summarize_hash')
        batch_op.drop_column('test2summarize')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry__post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test2summarize', sa.VARCHAR(length=214748364), nullable=True))
        batch_op.add_column(sa.Column('test2summarize_hash', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_entry__post_text2summarize_hash'))
        batch_op.drop_index(batch_op.f('ix_entry__post_text2summarize'))
        batch_op.create_index('ix_entry__post_test2summarize_hash', ['test2summarize_hash'], unique=False)
        batch_op.create_index('ix_entry__post_test2summarize', ['test2summarize'], unique=False)
        batch_op.drop_column('text2summarize_hash')
        batch_op.drop_column('text2summarize')

    # ### end Alembic commands ###
