"""new db

Revision ID: c4cc3164e899
Revises: 
Create Date: 2023-04-09 15:14:18.147732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cc3164e899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('posttype', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('text2summarize', sa.String(length=214748364), nullable=True),
    sa.Column('text2summarize_hash', sa.String(length=64), nullable=True),
    sa.Column('openAIsummary', sa.String(length=214748), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entry_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_post_openAIsummary'), ['openAIsummary'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry_post_posttype'), ['posttype'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry_post_text2summarize'), ['text2summarize'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry_post_text2summarize_hash'), ['text2summarize_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry_post_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry_post_url'), ['url'], unique=False)

    op.create_table('o_auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('linkedin_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('o_auth_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_o_auth_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_o_auth_user_linkedin_id'), ['linkedin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_o_auth_user_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_o_auth_user_timestamp'), ['timestamp'], unique=False)

    op.create_table('entry__posts__history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('entry_post_id', sa.Integer(), nullable=True),
    sa.Column('oAuthUser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_post_id'], ['entry_post.id'], ),
    sa.ForeignKeyConstraint(['oAuthUser_id'], ['o_auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entry__posts__history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry__posts__history_entry_post_id'), ['entry_post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry__posts__history_oAuthUser_id'), ['oAuthUser_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry__posts__history_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry__posts__history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry__posts__history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_entry__posts__history_oAuthUser_id'))
        batch_op.drop_index(batch_op.f('ix_entry__posts__history_entry_post_id'))

    op.drop_table('entry__posts__history')
    with op.batch_alter_table('o_auth_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_o_auth_user_timestamp'))
        batch_op.drop_index(batch_op.f('ix_o_auth_user_name'))
        batch_op.drop_index(batch_op.f('ix_o_auth_user_linkedin_id'))
        batch_op.drop_index(batch_op.f('ix_o_auth_user_email'))

    op.drop_table('o_auth_user')
    with op.batch_alter_table('entry_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_post_url'))
        batch_op.drop_index(batch_op.f('ix_entry_post_timestamp'))
        batch_op.drop_index(batch_op.f('ix_entry_post_text2summarize_hash'))
        batch_op.drop_index(batch_op.f('ix_entry_post_text2summarize'))
        batch_op.drop_index(batch_op.f('ix_entry_post_posttype'))
        batch_op.drop_index(batch_op.f('ix_entry_post_openAIsummary'))

    op.drop_table('entry_post')
    # ### end Alembic commands ###
