"""entry_post table

Revision ID: dd3ff32ed28c
Revises: 2a534d70df8e
Create Date: 2023-03-16 23:37:21.830020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3ff32ed28c'
down_revision = '2a534d70df8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry__post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posttype', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_entry__post_type')
        batch_op.create_index(batch_op.f('ix_entry__post_posttype'), ['posttype'], unique=False)
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry__post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_entry__post_posttype'))
        batch_op.create_index('ix_entry__post_type', ['type'], unique=False)
        batch_op.drop_column('posttype')

    # ### end Alembic commands ###
